language: php

php:
  - 7.1
  - 7.2

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database Qitsune;'
  - composer self-update
  - composer install --prefer-source --no-interaction
  - php artisan vendor:publish --tag=laravelroles
  - php artisan key:generate
  - php artisan migrate:install --env=testing --no-interaction
  - composer dump-autoload
  - sudo chgrp -R www-data storage bootstrap/cache
  - sudo chmod -R ug+rwx storage bootstrap/cache

language: node_js

node_js:
  - "8"
  - "10"

before_script:
  - yarn
  - yarn production
