<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\OverwatchController
 */
class OverwatchControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('overwatch'));

        $response->assertOk();
        $response->assertViewIs('overwatch.overwatch');
        $response->assertViewHas('tn');

        // TODO: perform additional assertions
    }

    // test cases...
}
