<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\PassedController
 */
class PassedControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('passed'));

        $response->assertOk();
        $response->assertViewIs('passed.passed');
        $response->assertViewHas('participations');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function set_flag_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('do-passed'));

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    // test cases...
}
